package org.kie.test;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class InvoiceLine  implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.Double total;

    private java.lang.String article;

    private java.lang.Integer line;

    private java.lang.Double unitPrice;

    private java.lang.Integer units;

    public InvoiceLine() {

    }

    public java.lang.Double getTotal() {
        return this.total;
    }

    public void setTotal(  java.lang.Double total ) {
        this.total = total;
    }

    public java.lang.String getArticle() {
        return this.article;
    }

    public void setArticle(  java.lang.String article ) {
        this.article = article;
    }

    public java.lang.Integer getLine() {
        return this.line;
    }

    public void setLine(  java.lang.Integer line ) {
        this.line = line;
    }

    public java.lang.Double getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(  java.lang.Double unitPrice ) {
        this.unitPrice = unitPrice;
    }

    public java.lang.Integer getUnits() {
        return this.units;
    }

    public void setUnits(  java.lang.Integer units ) {
        this.units = units;
    }

    @Override
    public String toString() {
        return "InvoiceLine{" +
                "line=" + line +
                ", article='" + article + '\'' +
                ", unitPrice=" + unitPrice +
                ", units=" + units +
                ", total=" + total +
                '}';

    }
}