package org.kie.test;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class SubComponent  implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.Integer d;

    private java.lang.String name;

    private java.util.Date birthDate;

    public SubComponent() {

    }

    public java.lang.Integer getD() {
        return this.d;
    }

    public void setD(  java.lang.Integer d ) {
        this.d = d;
    }

    public java.lang.String getName() {
        return this.name;
    }

    public void setName(  java.lang.String name ) {
        this.name = name;
    }

    public java.util.Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(  java.util.Date birthDate ) {
        this.birthDate = birthDate;
    }




}

