package org.kie.test;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class TestFormulas  implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.Integer result;

    private java.lang.Integer b;

    private java.lang.Integer c;

    private org.kie.test.SubComponent subc;

    private java.lang.Integer a;

    public TestFormulas() {

    }

    public java.lang.Integer getResult() {
        return this.result;
    }

    public void setResult(  java.lang.Integer result ) {
        this.result = result;
    }

    public java.lang.Integer getB() {
        return this.b;
    }

    public void setB(  java.lang.Integer b ) {
        this.b = b;
    }

    public java.lang.Integer getC() {
        return this.c;
    }

    public void setC(  java.lang.Integer c ) {
        this.c = c;
    }

    public org.kie.test.SubComponent getSubc() {
        return this.subc;
    }

    public void setSubc(  org.kie.test.SubComponent subc ) {
        this.subc = subc;
    }

    public java.lang.Integer getA() {
        return this.a;
    }

    public void setA(  java.lang.Integer a ) {
        this.a = a;
    }




}
