package org.kie.test;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class TestTypes  implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.math.BigDecimal useBigDecimal;

    private java.lang.Double useDouble;

    private java.lang.Boolean useBoolean;

    private java.lang.Integer useInteger;

    private java.lang.Long useLong;

    private java.util.List<org.kie.test.TestTypesLine> lines;

    private java.util.Date useDate;

    private java.lang.Float useFloat;

    private java.lang.Short useShort;

    private java.lang.String useString;

    public TestTypes() {

    }

    public java.math.BigDecimal getUseBigDecimal() {
        return this.useBigDecimal;
    }

    public void setUseBigDecimal(  java.math.BigDecimal useBigDecimal ) {
        this.useBigDecimal = useBigDecimal;
    }

    public java.lang.Double getUseDouble() {
        return this.useDouble;
    }

    public void setUseDouble(  java.lang.Double useDouble ) {
        this.useDouble = useDouble;
    }

    public java.lang.Boolean getUseBoolean() {
        return this.useBoolean;
    }

    public void setUseBoolean(  java.lang.Boolean useBoolean ) {
        this.useBoolean = useBoolean;
    }

    public java.lang.Integer getUseInteger() {
        return this.useInteger;
    }

    public void setUseInteger(  java.lang.Integer useInteger ) {
        this.useInteger = useInteger;
    }

    public java.lang.Long getUseLong() {
        return this.useLong;
    }

    public void setUseLong(  java.lang.Long useLong ) {
        this.useLong = useLong;
    }

    public java.util.List<org.kie.test.TestTypesLine> getLines() {
        return this.lines;
    }

    public void setLines(  java.util.List<org.kie.test.TestTypesLine> lines ) {
        this.lines = lines;
    }

    public java.util.Date getUseDate() {
        return this.useDate;
    }

    public void setUseDate(  java.util.Date useDate ) {
        this.useDate = useDate;
    }

    public java.lang.Float getUseFloat() {
        return this.useFloat;
    }

    public void setUseFloat(  java.lang.Float useFloat ) {
        this.useFloat = useFloat;
    }

    public java.lang.Short getUseShort() {
        return this.useShort;
    }

    public void setUseShort(  java.lang.Short useShort ) {
        this.useShort = useShort;
    }

    public java.lang.String getUseString() {
        return this.useString;
    }

    public void setUseString(  java.lang.String useString ) {
        this.useString = useString;
    }

    @Override
    public String toString() {
        String result = "TestTypes{" +
                "useBigDecimal=" + useBigDecimal +
                ", useDouble=" + useDouble +
                ", useBoolean=" + useBoolean +
                ", useInteger=" + useInteger +
                ", useLong=" + useLong +
                ", lines=" + lines +
                ", useDate=" + useDate +
                ", useFloat=" + useFloat +
                ", useShort=" + useShort +
                ", useString='" + useString + '\'';

        if (lines != null) {
            for (TestTypesLine line : lines) {
                result += "\\n";
                result += "line: " + line;
            }
        }
        result += '}';

        return result;
    }
}