package org.jbpm.examples.data;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class User  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer age;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String name;

    public User() {
    }

    public User(java.lang.String name, java.lang.Integer age) {
        this.name = name;
        this.age = age;
    }


    
    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(  java.lang.Integer age ) {
        this.age = age;
    }
    
    public java.lang.String getName() {
        return this.name;
    }

    public void setName(  java.lang.String name ) {
        this.name = name;
    }

    public String toString() {
        return "[Name="+name+", age="+age+"]";
    }


}